#inDir=/Users/ativ2716/testing/broadPeak inFile=c28.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=c29.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=c37.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=COLO205.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=CRC17A.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=CRC23A.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=CRC6A.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=CRC7A.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=crypt5.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=HCT116.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=SW480.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V1009.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V1024.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V1051.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V1058.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V1074.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V1106.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V206.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V389.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V410.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V411.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V429.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V456.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V481.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V576.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V5.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V784.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V852.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V855.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V866.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V940.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
inDir=/Users/ativ2716/testing/broadPeak inFile=V968.h3k27ac.uniq_peaks.broadPeak.bed.gz sbatch giggleSearch.q
